runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  max_concurrent_requests: 40

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
  secure: always
  redirect_http_response_code: 301

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always
  redirect_http_response_code: 301

- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301

- url: /_ah/warmup
  script: mirror.app
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: mirror.app
  secure: always
  redirect_http_response_code: 301
