runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  max_concurrent_requests: 40

handlers:
- url: /_ah/warmup
  script: mirror.app
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: mirror.app
  secure: always
  redirect_http_response_code: 301
